version: '3.8'

services:
  app:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: sh -c "npm install && npm run backend"
